### ISSUE TITLE
Pull discarded

### ISSUE THREAD

**Issue by talljoy** [bywatersolutions/koha-plugin-storage#8]
This workflow is a bit convoluted.  I'm open to suggestions for improving it.  

1. They need to run a report by callnumber (or call number range) and sort the results by branchcode and stocknumber

2. THey send the list of barcodes to (Rosemary/Gail/Jana??).  That individual approves the list or removes items from that list.

3. She sends confirmation back to them

4. They pull the books and discard them.

**Comment by kidclamp** [comment]
There is now  a report - it takes a callnumber range and returns items held by rstore or wrhse marked as discarded.

The report can be saved to csv to email to the interested party

The returned list should then be fed into reshelve report to generate the pull list

Assuming items are to be deleted form catalog I would suggest using the built in batch item deletion tool - we can provide a link within the plugin to thsi tool if needed

**Comment by todds1vtedu** [comment]
Joy didn't have it quite right.
1. We have a pile of papers (currently) each one indicating a Call Number to discard, usually Journals but it **can be** monographs. Sometimes it shows just a range of volumes of a journal to discard instead of pulling "all volumes."
2. We generally make a pull list of several of the call numbers so that we have ~200 items to pull at once.
3. We print the list.
4. We pull the list.
5. We scan the actual items into a text file so that we have a list of actual items pulled.
6. We send/email the list to Rosemary (Tech Services), who remove the entries from Koha/Sierra, and verify 
      1. if we missed pulling something we should have or
      2. incorrectly pulled something we should NOT have pulled
7) They send/email us a list of corrections to pull or put back
8) We do that and discard (recycle) the verified items

**Comment by kidclamp** [comment]
Okay, it sounds like this process should work with the plugin. You can now enter callnumbers, see a running total, and print just the results. Everything else should work just the same

**Comment by todds1vtedu** [comment]
Q1 .N55
q1 .n55 sec.A
q1 .n55 sec.B
q1 p55

If you use this as input, you see that each call number is sorted, which is not what we need. We need the whole list sorted so that if 2 or more call numbers are in the same box/location, they are together in the list.  The whole list needs to be sorted, not just within a call number.

**Comment by todds1vtedu** [comment]
Pull Discards doesn't seem to return anything at all since the new load.
i.e. nothing is displayed.

**Comment by todds1vtedu** [comment]
It seems to be producing output fine.

**Comment by todds1vtedu** [comment]
I do not know what is happening. when you put a call number in and click the Display Results button, it might just be taking several minutes to display or something I think. But if you click Display Results, wait a few seconds, then refresh the page, the table displays right away. If you add a second/third/additional call number and hit Display Results, then it is either taking a long time or you again can hit refresh the page, and the table displays.  Something is screwy, but refreshing the page is a work around.

**Comment by todds1vtedu** [comment]
I think this is fixed, but did anyone work on this or did it just heal itself?

**Comment by kidclamp** [comment]
Hi Todd, 

I think this was a caching issue that should now be resolved.

-Nick

**Comment by todds1vtedu** [comment]
Can you truncate the Title to just the first 20 char on this report like the others. We really don't focus on the Title a lot, and it takes a lot of space on the printouts.

**Comment by kidclamp** [comment]
Title shortened, will install latest version soon, closing this, please open a new issue for further changes
